version: "3"
services:
  server:
    build: ./server
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        NEXT_PUBLIC_API_SERVER_URL: http://localhost:5000
    ports:
      - "3000:3000"
    restart: always
